In [1]:
import pandas as pd

In [3]:
#Q1. Pandas version
pd.__version__

'3.0.6'

In [9]:
#Getting the data
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [23]:
df["acceleration"]
df["acceleration"].isna().sum()

np.int64(264)

In [12]:
#Q3 Fuel type : How many fuel types are presented in the dataset?
df.describe(include="all")
#3 different fuel types

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000,10000,10000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
unique,NaN,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,USA,Gasoline,Front-wheel drive,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,4202,6913,5519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1999.549500,NaN,NaN,NaN,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,NaN,NaN,NaN,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,NaN,NaN,NaN,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,NaN,NaN,NaN,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,NaN,NaN,NaN,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,NaN,NaN,NaN,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,NaN,NaN,NaN,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [24]:
#Q4 : Missing values How many columns in the dataset have missing values?
df.isnull().any()

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

In [37]:
#Q5 Max fuel intensity : What's the maximum fuel efficiency of cars from Asia?
filter = df[df['origin']=="Asia"]
#filter
filter.describe(include="all")

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,2994.000000,2994,2994,2994,2994.000000,2994.000000,2994.000000,2729.000000,2994.000000,2994.000000,2994.000000
unique,NaN,1,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Asia,Gasoline,Front-wheel drive,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2994,2082,1672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1999.436540,NaN,NaN,NaN,3.498664,2252.448230,5.998998,247.662514,4235.003340,18.897829,30.741015
std,14.251106,NaN,NaN,NaN,0.950582,184.008122,0.552308,21.321483,263.520367,1.315201,2.835474
min,1975.000000,NaN,NaN,NaN,2.000000,1590.000000,4.000000,174.000000,3320.000000,14.400000,21.300000
25%,1987.000000,NaN,NaN,NaN,3.000000,2130.000000,6.000000,234.000000,4060.000000,18.000000,28.700000
50%,1999.000000,NaN,NaN,NaN,4.000000,2260.000000,6.000000,248.000000,4230.000000,18.900000,30.700000
75%,2012.000000,NaN,NaN,NaN,4.000000,2370.000000,6.000000,262.000000,4410.000000,19.800000,32.500000
max,2024.000000,NaN,NaN,NaN,5.000000,3020.000000,8.000000,334.000000,5280.000000,23.800000,41.200000

In [42]:
#Q6 Most frequent value
#med = 254

# Médiane initiale (les valeurs manquantes sont ignorées)
median_before = df['horsepower'].median()
print("Médiane avant :", median_before)

# 1. Valeur la plus fréquente
most_frequent = df['horsepower'].mode()[0]
print("Valeur la plus fréquente :", most_frequent)

# 2. Remplir les valeurs manquantes avec cette valeur
df['horsepower'] = df['horsepower'].fillna(most_frequent)

# 3. Nouvelle médiane
median_after = df['horsepower'].median()
print("Médiane après :", median_after)

Médiane avant : 254.0
Valeur la plus fréquente : 252.0
Médiane après : 252.0

In [43]:
import numpy as np

# 1. Voitures d'Asie
df_asia = df[df['origin'] == 'Asia']

# 2. Colonnes vehicle_weight et model_year
df_asia = df_asia[['vehicle_weight', 'model_year']]

# 3. Les 7 premières lignes
df_asia = df_asia.head(7)

# 4. Tableau NumPy
X = df_asia.values

# 5. Produit X^T X
XTX = X.T.dot(X)

# 6. Inverse
XTX_inv = np.linalg.inv(XTX)

# 7. Vecteur y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# 8. w = (X^T X)^-1 X^T y
w = XTX_inv.dot(X.T).dot(y)
print("w =", w)

# 9. Somme des éléments
print("Somme :", w.sum())

w = [0.13644777 0.2327492 ]
Somme : 0.36919696904925486