# Homework 3 : Classification

**Auteur :** Anis-Samy Laamri
**Date :** October 2026

Dataset : *2026 lead-scoring* https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
from sklearn.model_selection import train_test_split

from IPython.display import display
from sklearn.metrics import mutual_info_score
from sklearn.feature_extraction import DictVectorizer

---
## Introduction : Dataset and preparing the dataset.

In this dataset our desired target for classification task will be converted variable - has the client signed up to the platform or not.

In [2]:
#Getting the data
df = pd.read_csv('course_lead_scoring_2026.csv')
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

---
### Check of the missing values are presented in the features

If there are missing values: <br>
For categorical features, replace them with 'NA' <br>
For numerical features, replace with with 0.0

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
0,2180,243.0,3870,2006,31.9
1,2390,272.0,4210,2008,31.3
2,2320,267.0,4240,1996,27.5
3,2130,258.0,4490,1989,28.5
4,2580,304.0,4510,1994,31.0
...,...,...,...,...,...
9995,2470,271.0,4690,2005,27.4
9996,2300,244.0,4370,1993,30.0
9997,2480,267.0,4590,2014,28.1
9998,2180,270.0,4450,2004,32.2
9999,2380,295.0,4370,2011,30.2

---
## Question 1 : What is the most frequent observation (mode) for the column *industry*?

NA <br>
technology <br>
healthcare <br>
retail <br>

engine_displacement    False
horsepower              True
vehicle_weight         False
model_year             False
fuel_efficiency_mpg    False
dtype: bool

### Horsepower is the column with missing values

---
## Question 2 : What are the two features that have the biggest correlation?

Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features. <br>

interaction_count and lead_score <br>
number_of_courses_viewed and lead_score <br>
number_of_courses_viewed and interaction_count <br>
annual_income and interaction_count <br>
Only consider the pairs above when answering this question. <br>

### The median for variable 'horsepower' is 254

---
### Prepare and split the dataset:

Split the data with these exact calls <br>
Make sure that the target value converted is not in your dataframe.

In [ ]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

---
## Question 3 : Which of these variables has the biggest mutual information score?

Calculate the mutual information score between converted and other categorical variables in the dataset. Use the training set only. Round the scores to 2 decimals using round(score, 2). <br>

industry <br>
location <br>
lead_source <br>
employment_status <br>

In [154]:
print("RMSE avec mean :", round(rmse(y_train, y_pred), 3))

RMSE avec mean : 2.199

---
## Question 4 : Logistic regression

Now let's train a logistic regression.<br>
Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.<br>
Fit the model on the training dataset.<br>
To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:<br>
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)<br>
Calculate the accuracy on the validation dataset and round it to 2 decimal digits.<br>
What accuracy did you get?<br>

0.55<br>
0.65<br>
0.75<br>
0.85<br>

0 2.207
0.01 2.2067
0.1 2.2195
1 2.3364
5 2.3952
10 2.4051
100 2.4146

---
## Question 5 : Reduction of model's parameters

Let's find the least useful feature using the feature elimination technique.<br>
Train a model using the same features and parameters as in Q4 (without rounding).<br>
Now exclude each feature from this set and train a model without it. Record the accuracy for each model.<br>
For each feature, calculate the difference between the original accuracy and the accuracy without the feature.<br>
Which of following feature has the smallest difference?

'lead_source'<br>
'number_of_courses_viewed'<br>
'interaction_count'<br>

Note: The difference doesn't have to be positive.

0 2.239
1 2.202
2 2.163
3 2.204
4 2.202
5 2.246
6 2.27
7 2.191
8 2.217
9 2.207
Écart-type : 0.029

---
## Question 6 : Regularized logistic regression

Now let's train a regularized logistic regression.<br>
Let's try the following values of the parameter C: [0.000001, 0.00001, 0.0001, 0.001].<br>
Train models using all the features as in Q4.<br>
Calculate the accuracy on the validation dataset and round it to 3 decimal digits.<br>
Which of these C leads to the best accuracy on the validation set?<br>

0.000001<br>
0.00001<br>
0.0001<br>
0.001<br>

Note: If there are multiple options, select the smallest C.